### ISSUE TITLE
Adding nonstatic tags

### ISSUE THREAD

**Issue by ItsReddi** [mitoeurope/yii2-sentry#10]
Its is allready possible to add Tags that are not static?
Did not found a way.

Something like:
`
            'client' => [
                'tags' => ['nonstatictag' => function(){ return $_SESSION['somesessionvalue'] ?? 'default'; } ]
            ],
`
would be helpful.

**Comment by albertborsos** [comment]
If it did not work, then you can not. 

But, you can add tags in runtime like this:
```php
Yii::$app->sentry->client->tags = ArrayHelper(Yii::$app->sentry->client->tags, ['key' => 'value']);
```

I tried to add a helper method for this, but the tests are failed at the mocked `Raven_Client`. So I need to look after it a bit more.
