### ISSUE TITLE
A callback or event after sending to sentry is needed

### ISSUE THREAD

**Issue by danaki** [mitoeurope/yii2-sentry#11]
Hello, I need to show client a nice error page with an error id. After digging into Raven code I see that it returns an event_id that can suit my purposes, but SentryTarget::export() silently drops it just because it's only log target nothing more. It's definitely a bad idea to break the loose coupling and introduce an external storage like session to store the event_id in yii2-sentry component, but I guess that an event publish just after the sentry->captureException() would be a better way to save event_id for future use. What do you think?

**Comment by albertborsos** [comment]
Why would you like to show error id to the client?

**Comment by danaki** [comment]
This is the requirement of my customer. There must be an error id on the page that user can submit to support.

**Comment by albertborsos** [comment]
When an error occurs, you can find it in sentry.io or in your self-hosted sentry. (submitted to the support) Where you can identify the user who had the error.

I do not feel it as a common issue, but you are free to fork and extend it for your needs.

**Comment by nkovacs** [comment]
There's no guarantee that the error message will be dispatched to sentry before you render your error page. Yii's error handler will just log the error using `Yii::error`, it'll be dispatched when Logger flushes the log. This can happen as late as shutdown: https://github.com/yiisoft/yii2/blob/c19b2f7dc8f487f0a867f2cacab68b8e86b7a8f9/framework/log/Logger.php#L124
