### ISSUE TITLE
More environment out of tags to the root

### ISSUE THREAD

**Issue by michaelarnauts** [mitoeurope/yii2-sentry#14]
raven-js sets the environment in the root configuration array instead of inside the tags. See https://docs.sentry.io/clients/javascript/config/#optional-settings

I've changed this in an (outdated) commit on my banch: https://github.com/michaelarnauts/yii2-sentry/commit/68a7dd461eb41b79246d07d7f1a3b88962ec2de5

Is this something that can be included in this branch?

**Comment by nkovacs** [comment]
Closing, since the PR has been merged. Thanks.
