### ISSUE TITLE
No matching package found

### ISSUE THREAD

**Issue by varp** [mitoeurope/yii2-sentry#21]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mito/yii2-sentry 1.0.2 requires bower-asset/raven-js 3.12.* -> no matching package found.
    - mito/yii2-sentry 1.0.1 requires bower-asset/raven-js 3.12.* -> no matching package found.
    - mito/yii2-sentry 1.0.0 requires bower-asset/raven-js 3.12.* -> no matching package found.
    - Installation request for mito/yii2-sentry ~1.0.0 -> satisfiable by mito/yii2-sentry[1.0.0, 1.0.1, 1.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by nkovacs** [comment]
You either need [composer-asset-plugin](https://github.com/fxpio/composer-asset-plugin) or [asset-packagist](https://asset-packagist.org/) to install bower-asset/raven-js.
