### ISSUE TITLE
How fix CORS?

### ISSUE THREAD

**Issue by SlavaPWNZ** [mitoeurope/yii2-sentry#34]
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by albertborsos** [comment]
Can you explain your case please? CORS error occures when the connection between two machines are not secure. Do you use sentry.io or self hosted sentry? Do you use it from localhost or from a public server?

**Comment by SlavaPWNZ** [comment]
1) self hosted
2) Public server, but another domain name
![Снимок экрана от 2022-04-25 15-03-25](https://user-images.githubusercontent.com/34984584/165085509-2290903f-baeb-46aa-bc15-638f0058b13f.png)

**Comment by SlavaPWNZ** [comment]
fixed
https://github.com/getsentry/sentry-javascript/issues/2859#issuecomment-1108518806
